# @Author: Samuel Naranjo Rincón

identification:
  unique_ID: 2026_0918_adamW_ICA_PFM_SCHF100_SCHF200_SCHF300_GLSS360_MoE

data:
  topomaps: ["ICA", "PFM"]
  topo_dims: [15, 14]
  topo_prep: ["norm", "norm"]
  connectomes: ["schaefer", "schaefer", "schaefer", "glasser"]
  connectome_dims: [100, 200, 300, 360]
  connectome_prep: ["demean", "demean", "demean", "demean"]
  model_type: MoE
  icores: 2
  # sub_ids_path: '/ceph/chpc/shared/janine_bijsterbosch_group/WAPIAW_2026/qc/individual_subjects/individual_subject_list_highNSI_3001.txt'
  sub_ids_path: '/ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/CHIMERA-fMRI/utils/subj_ids/ABCDv6/ABCD_train_val_test_split_exp.csv'

logging:
  live_logfile: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/CHIMERA-fMRI/batch/train_{} #train_SiT_reconstruction_{}d{}_{}d{}
  model_output_path: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/CHIMERA-fMRI/model_out
  model_save_path: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/CHIMERA-fMRI/logs
  
training:
  fcn_train: train_fusion 
  dataset_choice: ABCDv6 # ABCD or HCPYA or HCPYA_ABCDdr or infomap_prior_ABCDdr
  overfit_condition: False
  bs: 32 # batch size, og is 256
  LR: 0.001 #0.00001 is original
  val_epoch: 1 #5 is our standard, arbitary so feel free to change.
  epochs: 300
  bilateral_condition: False #if true, uses 2LR, else just 1L
  hemi_cond: 1L
  finetune: False 
  
testing:
  immediate_test_flag: True #test after training immediately
  chosen_test_model: MSE #can be MSE, MAE, RHO
  same_sample_test: True # if this is true, then out of sample false and vice versa
  out_of_sample_test: False
  bs_test: 1

fusion_params:
  latent_dim: 10
  beta: 0.0 
  warmup_epochs: 30
  log_var_max: 200
  model_details: 2026_0918_adamW_ICA_PFM_SCHF100_SCHF200_SCHF300_GLSS360_MoE
  fusion_dim: 128
  pool_patches: True
  conn_hidden: 512
  # latent_fusion_type: poe #poe or moe
  n_iwae_samples: 1000 #for MoE number of resampling for latent Z

topomap_encoders:
  depth: 6 #layers # O(D*H*(V**x)) dont recall the exponent x but it scales apprx like this so not too high
  heads: 3 # D=depth=layer, 
  dim: 192 # tiny-192, small-384
  emb_dropout: 0.3
  dropout: 0.5 # moved this higher, was originall 0.1
  VAE_flag: False
  vae_dim: 100
  latent_samples: 100
  expert_name: topomap_recon

connectome_encoders:
  dim: 256 #64, 128, 256
  emb_dropout: 0.3
  dropout: 0.5 # moved this higher, was originall 0.1
  VAE_flag: False
  vae_dim: 100
  latent_samples: 100
  expert_name: connectome_recon

optimisation:
  optimiser: AdamW # SGD = stochastic gradent descent; Adam = Adam optimization

Adam:
  weight_decay: 0.001

AdamW:
  weight_decay: 0.001 #originally just this
  use_scheduler: True #orig is false, but in paper they said they did use scheduler=>cosine decay
  scheduler: CosineDecay  # CosineDecay, StepLR, ReduceLROnPlateau
  warmup: True
  nbr_step_warmup: 50
  
SGD:
  weight_decay: 0.
  momentum: 0.9
  nesterov: False
  
StepLR: 
  stepsize: 1000
  decay: 0.5

CosineDecay:
  T_max: 30 #5000. is original, # 25 for now because it seems to converge at that epoch which could be a local minima
  eta_min: 0.000001

CosineDecayRestart:
  T_0: 25 #Number of iterations until the first restart.
  T_mult: 1 #A factor by which T_i increases after a restart. Default: 1.
  eta_min: 0.00001
  
sub_ico_0:
    num_patches: 20 
    num_vertices: 2145 

sub_ico_1:
  num_patches: 80 
  num_vertices: 561 

sub_ico_2:
  num_patches: 320 
  num_vertices: 153

sub_ico_3:
    num_patches: 1280
    num_vertices: 45

sub_ico_4:
    num_patches: 5120
    num_vertices: 15

sub_ico_5:
    num_patches: 20480
    num_vertices: 6 