# @Author: Samuel Naranjo Rincón
# topomap_representations = ["ICA", "PFM", "GRAD", "NMF"] #TODO expand this list as we do more brain reps or get more
# connectome_representations = ["schaefer", "glasser", "kong", "MSHBM", "TM", "IM"]

identification:
  unique_ID: 2026_0903_d4h2_tiny_adamW_recon_schfd100_schfd100_LinearDecoder

data:
  data_type_input: schaefer
  input_dim: 100
  prep_type_input: demean
  data_type_output: schaefer
  output_dim: 100
  prep_type_output: demean
  model_type: linear
  sub_ids_path: '/ceph/chpc/shared/janine_bijsterbosch_group/WAPIAW_2026/qc/individual_subjects/individual_subject_list_highNSI_3001.txt'

logging:
  live_logfile: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/CHIMERA-fMRI/batch/train_{}_{}_{}d{}_{}d{}_{} #train_SiT_reconstruction_{}d{}_{}d{}
  model_output_path: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/CHIMERA-fMRI/model_out
  model_save_path: /ceph/chpc/shared/janine_bijsterbosch_group/naranjorincon_scratch/NeuroTranslate/CHIMERA-fMRI/logs
  
training:
  fcn_train: fcn_train #train_MSE_skewloss #train_krakenonly
  fcn_model_to_use: connectome_recon
  dataset_choice: ABCDv6 # ABCD or HCPYA or HCPYA_ABCDdr or infomap_prior_ABCDdr
  overfit_condition: True
  overfit_condition_sub_range: 100 # up to which subj, if overfit_condition false this is ignored
  bs: 32 # batch size, og is 256
  LR: 0.001 #0.00001 is original
  val_epoch: 1 #5 is our standard, arbitary so feel free to change.
  epochs: 4
  bilateral_condition: False #if true, uses 2LR, else just 1L
  hemi_cond: 1L
  finetune: False 
  
testing:
  immediate_test_flag: True #test after training immediately
  chosen_test_model: MSE #can be MSE, MAE, RHO
  same_sample_test: True # if this is true, then out of sample false and vice versa
  out_of_sample_test: False
  bs_test: 1

transformer:
  depth: 4 #layers # O(D*H*(V**x)) dont recall the exponent x but it scales apprx like this so not too high
  heads: 2 # D=depth=layer, 
  dim: 128 #embedding proportion, based on parcellation_size*0.1 so 10% or 0.2->20%
  # dim_head: 64 #64, 128
  emb_dropout: 0.3
  dropout: 0.5 # moved this higher, was originall 0.1
  model_details: 2026_0903_d4h2_tiny_adamW_recon_schfd100_schfd100_LinearDecoder
  VAE_flag: False
  vae_dim: 100
  latent_samples: 100
  decoder_name: LinearDecoder #LinearDecoder, ConvDecoder, PointwiseDecoder, GATDecoder #not working: MeshConvDecoder

optimisation:
  optimiser: AdamW # SGD = stochastic gradent descent; Adam = Adam optimization

Adam:
  weight_decay: 0.001

AdamW:
  weight_decay: 0.001 #originally just this
  use_scheduler: False #orig is false, but in paper they said they did use scheduler=>cosine decay
  scheduler: CosineDecay  # CosineDecay, StepLR, ReduceLROnPlateau
  warmup: True
  nbr_step_warmup: 50
  
SGD:
  weight_decay: 0.
  momentum: 0.9
  nesterov: False
  
StepLR: 
  stepsize: 1000
  decay: 0.5

CosineDecay:
  T_max: 30 #5000. is original, # 25 for now because it seems to converge at that epoch which could be a local minima
  eta_min: 0.000001

CosineDecayRestart:
  T_0: 25 #Number of iterations until the first restart.
  T_mult: 1 #A factor by which T_i increases after a restart. Default: 1.
  eta_min: 0.00001
  